// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-Lx4MYhPpalSK_UVS2YjJi2m1gDmI7U',
    appId: '1:1007404411041:web:b38ba504357c1fb8c468e0',
    messagingSenderId: '1007404411041',
    projectId: 'onetap365-3df10',
    authDomain: 'onetap365-3df10.firebaseapp.com',
    storageBucket: 'onetap365-3df10.firebasestorage.app',
    measurementId: 'G-YYFWQHJL7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8XnxK8Spekxh-q_aydd3EKbWkwxfS_E',
    appId: '1:1007404411041:android:40c002a2c1df6cb7c468e0',
    messagingSenderId: '1007404411041',
    projectId: 'onetap365-3df10',
    storageBucket: 'onetap365-3df10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7o7nyP9sbN46QpULgufd4JFq269BgsY',
    appId: '1:1007404411041:ios:be2a37b8048926aac468e0',
    messagingSenderId: '1007404411041',
    projectId: 'onetap365-3df10',
    storageBucket: 'onetap365-3df10.firebasestorage.app',
    iosBundleId: 'com.example.onetap365app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu7o7nyP9sbN46QpULgufd4JFq269BgsY',
    appId: '1:1007404411041:ios:be2a37b8048926aac468e0',
    messagingSenderId: '1007404411041',
    projectId: 'onetap365-3df10',
    storageBucket: 'onetap365-3df10.firebasestorage.app',
    iosBundleId: 'com.example.onetap365app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-Lx4MYhPpalSK_UVS2YjJi2m1gDmI7U',
    appId: '1:1007404411041:web:a29444e94d9523e9c468e0',
    messagingSenderId: '1007404411041',
    projectId: 'onetap365-3df10',
    authDomain: 'onetap365-3df10.firebaseapp.com',
    storageBucket: 'onetap365-3df10.firebasestorage.app',
    measurementId: 'G-Z96HHLDXT6',
  );
}
